Hw08 envdir tool
apabramov/hw-test pull request #10
Opened 2022-12-09 17:45 UTC by apabramov

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-12 21:29 UTC, vladislavmass requested changes
Работа хорошая. Но есть ряд недоработок, которые мешают принять работу

2022-12-12 21:29 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +			val = strings.TrimRight(val, " ")
Не учтен вариант когда вначале идет пробел, а после него табуляция

2022-12-12 21:29 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +			val := strings.TrimRight(string(s), "\r")
Отсутствует замена терминальных нулей на перенос строки

2022-12-12 21:29 UTC, vladislavmass commented on hw08_envdir_tool/executor.go
> +			if err != nil {
В задние есть условие что название папки не будет содержать пробел. Сейчас проверка осуществляется не в вашем коде. Но тут есть 2 момент. 1) это может быть реализовано не везде 2) Если у нас есть файл с равно в имени, а его отсечение происходит только при установке переменных, то получается что вся работу, которая была сделана после считывания папок и до момента возникновения ошибки сделана зря.

2022-12-12 21:29 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		func() {
Не совсем понятно зачем внутри цикла создавать синхронную анонимную функцию .

2022-12-13 12:42 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +		func() {
Чтобы реализовать defer внутри цикла

2022-12-13 12:43 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +			val := strings.TrimRight(string(s), "\r")
[]byte{0} - это терминальный ноль

2022-12-13 12:52 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +			val = strings.TrimRight(val, " ")
добавил
val = strings.TrimRight(val, "\t")

2022-12-13 13:02 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +			val := strings.TrimRight(string(s), "\r")
Уберите пожалуйста магические числа 0 и 10 из кода. Так как это снижает читаемость кода.

2022-12-13 13:04 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +		func() {
Может просто в конце цикла закрыть файл. если произойдет паника то операционная система сама закроет все потоки.

2022-12-13 13:11 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +			val := strings.TrimRight(string(s), "\r")
И момент почему это не так. Тут идет замена 0 на 10. А что будет если внутри файла у нас много байтовая кодировка, например китайский язык, и один из байтов будет 0. И все эти нули заменятся на 10. Тем самым строка станет не валидной.

2022-12-13 13:13 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +		func() {
убрал func

2022-12-13 13:14 UTC, apabramov commented on hw08_envdir_tool/executor.go
> +			if err != nil {
Добавил проверку

2022-12-13 13:14 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +			val := strings.TrimRight(string(s), "\r")
Заменил на strings.ReplaceAll(str, "\u0000", "\n")

2022-12-13 18:52 UTC, apabramov commented on hw08_envdir_tool/env_reader.go
> +			val = strings.TrimRight(val, " ")
Добавил функцию

2022-12-19 06:05 UTC, HangryHoneyBadger approved these changes
Работа принята. 10/10

2022-12-20 13:48 UTC, vladislavmass approved these changes
Работа принята

2022-12-20 13:57 UTC, merged