stats_optimization_test.go:46: time used: 177.1399ms / 300ms
apabramov/hw-test pull request #13
Opened 2022-12-30 14:11 UTC by apabramov

stats_optimization_test.go:46: time used: 177.1399ms / 300ms
    stats_optimization_test.go:47: memory used: 3Mb / 30Mb
--- PASS: TestGetDomainStat_Time_And_Memory (2.37s)
PASS
ok      github.com/apabramov/hw-test/hw10_program_optimization    2.797s

## Домашнее задание №10 «Оптимизация программы»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2022-12-31 08:03 UTC, dshemin requested changes

2022-12-31 08:03 UTC, dshemin commented on hw10_program_optimization/stats.go
> +	for _, user := range u {
Важно: 

Есть простор для оптимизации дальше: Обратите внимание что сейчас у нас обрабатывается всё в два цикла. В первом мы унмаршалим данный структуры и складываем в массив. Во втором цикле обходим массив и аггрегируем.

В итоге мы дважды итерируемся по N элементов и выделяем память для N элементов. Можно сделать в один цикл и с константным потреблением памяти.

2023-01-06 14:59 UTC, apabramov commented on hw10_program_optimization/stats.go
> +	for _, user := range u {
Убрал второй цикл

2023-01-07 09:36 UTC, dshemin approved these changes

2023-01-07 09:36 UTC, dshemin commented on hw10_program_optimization/stats.go
> +		if strings.Contains(user.Email, d.String()) {
Важно:

`d.String` не зависит от цикла, поэтому может быть вычислен один раз, до цикла, и переиспользован.

2023-01-07 09:36 UTC, dshemin commented on hw10_program_optimization/stats.go
> +			result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]++
Важно:

Что случится если у нас в `user.Email` будет строка "foo" или "bar@"  или "@fizz"? Обработайте и напишите тесты.

2023-01-08 10:19 UTC, apabramov commented on hw10_program_optimization/stats.go
> +		if strings.Contains(user.Email, d.String()) {
Вынес за цикл.

2023-01-08 10:36 UTC, apabramov commented on hw10_program_optimization/stats.go
> +			result[strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])]++
Добавил тесты

2023-01-08 12:58 UTC, dshemin approved these changes

2023-01-08 19:14 UTC, merged