Hw13 calendar
apabramov/hw-test pull request #15
Opened 2023-01-25 20:53 UTC by apabramov

## Домашнее задание №13 «API к Календарю»

### Критерии оценки
- [ ] Makefile заполнен и пайплайн зеленый - 1 балл
- [ ] Реализовано GRPC API и `make generate` - 3 балла
- [ ] Реализовано HTTP API - 2 балла
- [ ] Написаны юнит-тесты на API - до 2 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-01-26 03:17 UTC, dshemin requested changes

2023-01-26 03:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	pbEvents := make([]*pb.Event, 0)
Важно:

Стоит указать capacity. В текущем коде мы инициализируем пустой слайс, который будет постоянно расти при добавлении новых элементов, если его capacity будет превышен. Рост слайса - это выделение новой памяти и копирование элементов. Растёт по степеням двойки - 1, 2, 4, 8 ...

Например:

Если у вас в Events будет 20 элементов, то:
1. При добавлении первого элемента в pbEvents будет выделение памяти, слайс станет размером 1
2. При добавлении второго элемента - выделение и копирование, слайс станет размером 2.
3. При добавлении 3 элемента - выделение и копирование, слайс станет размером 4
4. При добавлении 5 элемента - выделение и копирование, слайс станет размером 8

и т.д. Операции выделения и копирования - не бесплатны. Плюсом, такой алгоритм в итоге может выделить памяти больше чем нам надо.

Учитывая то, что тут нам заранее известно сколько элементов у нас будет - то всё этого можно легко избежать.

2023-01-26 03:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +//func TestGRPCServerDel(t *testing.T) {
Важно:

Если код не нужен, его стоит удалять.

2023-01-26 03:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +type Application interface {
Важно:

Если верно понимаю, этот интерфейс нам тут не нужен.

2023-01-26 03:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/app/app.go
> +	return a.Store.ListByDay(ctx, dt)
Важно:

Насколько вижу, ответственность за вычисление конкретной промежутка времени, за который нам надо найти события, мы перекладываем на сторадж. А у нас их два. И они оба будут делать одно и тоже. Кажется более логично сделать это в сервисе и в репозиторий передать уже конкретные даты начала и конца промежутка. Так мы избежим копирование логики.

2023-01-26 03:17 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.Log.Info(fmt.Sprintf("HTTP stopping:  %v:%v", s.Host, s.Port))
Важно:


Надо выполнить shutdown

2023-01-26 09:18 UTC, apabramov commented on hw12_13_14_15_calendar/Makefile
> +generate:
Есть строка
generate:
	protoc --go_out=internal/server/pb --go-grpc_out=internal/server/pb --grpc-gateway_out=internal/server/pb --grpc-gateway_opt generate_unbound_methods=true --openapiv2_out . api/*.proto

Она генерирует код. разве не это нужно?

2023-01-26 10:19 UTC, apabramov commented on hw12_13_14_15_calendar/api/EventService.proto
> +  rpc Add(EventRequest) returns (ErrorResponse){
Добавил в ответ Event

2023-01-26 10:20 UTC, apabramov commented on hw12_13_14_15_calendar/api/EventService.proto
> +  rpc Get(IDRequest) returns (Event){
Изменил ответ

2023-01-26 10:24 UTC, apabramov commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	startGRPC(ctx, &config, logg, calendar)
Я использовал  https://grpc-ecosystem.github.io/grpc-gateway/
Т.е. это reverse proxy обертка над GPRC.

В этом случае HTTP сервер может остановить раньше?

2023-01-26 11:29 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/grpc/server_test.go
> +//func TestGRPCServerDel(t *testing.T) {
Исправил

2023-01-26 11:36 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +type Application interface {
Удалил

2023-01-26 11:36 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	pbEvents := make([]*pb.Event, 0)
Добавил

2023-01-26 11:38 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.Log.Info(fmt.Sprintf("HTTP stopping:  %v:%v", s.Host, s.Port))
Я использовал https://grpc-ecosystem.github.io/grpc-gateway/
Т.е. это reverse proxy обертка над GPRC.

Для reverse proxy нужен shutdown?
Не нашел его?

2023-01-26 11:59 UTC, apabramov commented on hw12_13_14_15_calendar/internal/app/app.go
> +	return a.Store.ListByDay(ctx, dt)
Изменил

2023-01-27 03:05 UTC, dshemin requested changes

2023-01-27 16:25 UTC, apabramov commented on hw12_13_14_15_calendar/Makefile
> +generate:
Реализовал

2023-01-27 16:25 UTC, apabramov commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	startGRPC(ctx, &config, logg, calendar)
Реализовал

2023-01-27 16:26 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	s.Log.Info(fmt.Sprintf("HTTP stopping:  %v:%v", s.Host, s.Port))
Изменил

2023-01-27 16:27 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/grpc/server.go
> +	events, err := s.App.ListByDayEvents(ctx, t, t.AddDate(0, 0, 1))
Вынес выше

2023-01-28 03:10 UTC, dshemin approved these changes

2023-01-28 03:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		log.Info(err.Error())
Важно:

Сейчас только заметил, если произошла ошибка, мы продолжим нормальное выполнение, покв не попытаемся орбратится к srv.Srv или srv.Mux и не упадём с паникой при попытке разыменовать nil указатель.

Лучше вернуть данную ошибку и обработать.

2023-01-28 03:10 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	if err != nil {
Важно:

Обработка ошибки должна быть сразу же после того места где она возникла.

2023-01-28 22:46 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +		log.Info(err.Error())
Вернул ошибку

2023-01-28 22:46 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server.go
> +	if err != nil {
Перенес

2023-01-28 23:03 UTC, apabramov commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +	startGRPC(ctx, &config, logg, calendar)
Объединил функции

2023-01-29 06:49 UTC, dshemin approved these changes

2023-01-29 06:49 UTC, dshemin commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		logg.Info(err.Error())
Важно:

Смотрите, мы не смогли создать сервер, залогировали это и потом продолжаем пытаться его запускать. Да, вы добавили проверку на nil, но наш сервер, согласно заданию, обязан предоставлять одновременно и REST и gRPC интерфейс.

2023-01-29 06:49 UTC, dshemin commented on hw12_13_14_15_calendar/internal/server/http/server_test.go
> +	_, err = grpc.Dial(l.Addr().String(), clientOptions...)
Важно:

Возьмите за правило, если функция возвращает ошибку, её надо сразу обработать. Тут мы опять имеем ошибку, которая никак не проверяется. Да, это тест, но если что-то пойдёт не так, мы будем видеть ошибку не там где она возникла и нам будет трудно понять что не так.

2023-01-29 14:23 UTC, apabramov commented on hw12_13_14_15_calendar/internal/server/http/server_test.go
> +	_, err = grpc.Dial(l.Addr().String(), clientOptions...)
Добавил require

2023-01-29 14:23 UTC, apabramov commented on hw12_13_14_15_calendar/cmd/calendar/main.go
> +		logg.Info(err.Error())
Добавил return

2023-01-29 14:25 UTC, merged