Hw05 parallel execution
apabramov/hw-test pull request #7
Opened 2022-11-01 10:49 UTC by apabramov

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-11-01 19:52 UTC, Nikscorp requested changes
Алексей, добрый вечер!

Работа выполнена в соответствии с ТЗ, однако на данный момент я не готов ее принять.

Есть замечания по структуре и чистоте кода, проверке граничных значений: вычтен 1 балл
Из юнит тестов добавлен только тест с `eventually` практически идентичный тесту со слипом: вычтено 3 балла

Текущий результат: 6 баллов, зачет от 7 баллов.

Уверен испралвение замечаний не вызовет у вас трудностей и позволит лучше разобраться в теме.

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run_test.go
> +	t.Run("tasks without errors without sleep", func(t *testing.T) {
sleep в тесте и потенциальные проблемы из него вытекающие остались

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +type Worker struct {
думаю структура воркера здесь избыточна. В каждой горутине используется ровно половина полей, лучше передавать их просто как аргументы в функцию или использовать замыкание

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +func IsClosed(ch <-chan struct{}) bool {
публичная функция, которая должна быть приватной

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +		fmt.Println(res)
можно убрать отладочную печать

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run.go
> +	outErr chan error
логика с каналом ошибок валидная, но немного переусложненная и приводит к излишнему выделению памяти.
Так как нам нужно трекать только количество ошибок, можно просто учитывать их в int переменной (используя мьтекс / атомик / ...).

Такое решение будет выглядеть более естественно и читаться проще.

2022-11-01 19:52 UTC, Nikscorp commented on hw05_parallel_execution/run.go
>  func Run(tasks []Task, n, m int) error {
не обрабатываются значения n, m < 0, на данные значения нет юнит тестов

2022-11-07 15:00 UTC, apabramov commented on hw05_parallel_execution/run.go
> +type Worker struct {
Удалил структуру

2022-11-07 15:00 UTC, apabramov commented on hw05_parallel_execution/run.go
> +func IsClosed(ch <-chan struct{}) bool {
Удалил функцию

2022-11-07 15:00 UTC, apabramov commented on hw05_parallel_execution/run.go
> +		fmt.Println(res)
Убрал

2022-11-07 15:01 UTC, apabramov commented on hw05_parallel_execution/run.go
> +	outErr chan error
Использую atomic

2022-11-07 15:01 UTC, apabramov commented on hw05_parallel_execution/run.go
>  func Run(tasks []Task, n, m int) error {
Добавил валидацию

2022-11-07 18:55 UTC, Nikscorp approved these changes
Алексей, добрый день!

Отличная работа, все замечания исправлены, доп задание сделано.
Повышаю оценку до максимального балла (10).

2022-11-07 18:55 UTC, Nikscorp commented on hw05_parallel_execution/run_test.go
> +			return atomic.LoadInt32(&runTasksCount) == int32(workersCount)
отлично!

Правда не увидел тестов на отрицательные значения n, m, но за доп задание — пропускаю это замечание

2022-11-08 08:05 UTC, merged